services:
  frontend-prod:
    image: ozzydoc/finstream-frontend:prod
    container_name: finstream-frontend-prod
    restart: unless-stopped
    ports:
      - ${FRONTEND_PROD_PORT}:80
    networks:
      - prod

networks:
  prod:
    external: true
