quarkus.application.name=fn
%dev.quarkus.application.name=fn_dev
%qa.quarkus.application.name=fn_qa
%local.quarkus.application.name=fn_local

#Otel
quarkus.otel.logs.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.exporter.otlp.timeout=3
quarkus.otel.exporter.otlp.endpoint=http://lgtm:4317
%local.quarkus.otel.exporter.otlp.endpoint=http://3.136.184.49/grpc

#Hibernate
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/prod
quarkus.datasource.reactive.url=vertx-reactive:postgresql://postgres:5432/prod

%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/dev
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://postgres:5432/dev

%qa.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/qa
%qa.quarkus.datasource.reactive.url=vertx-reactive:postgresql://postgres:5432/qa

%local.quarkus.datasource.jdbc.url=jdbc:postgresql://3.136.184.49:5423/dev?sslmode=require
%local.quarkus.datasource.reactive.url=vertx-reactive:postgresql://3.136.184.49:5432/dev?sslmode=require

#Hibernate logging
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

#Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog_prod.yml

%dev.quarkus.liquibase.change-log=db/changelog_dev.yml
%qa.quarkus.liquibase.change-log=db/changelog_qa.yml
%local.quarkus.liquibase.change-log=db/changelog_dev.yml


